# Use an official Python runtime as a parent image
FROM python:3.12-alpine

# Set the working directory in the container
WORKDIR /app

# Install Pipenv
RUN pip install --no-cache-dir pipenv

# Copy the required files into the container
COPY Pipfile /app/Pipfile
COPY Pipfile.lock /app/Pipfile.lock

# Install dependencies
RUN pipenv install --system --deploy

# Expose the port the app runs on
EXPOSE 80

# Run the application
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"]
